
title: Peeragogy Handbook AI Edition
description: An AI-enhanced version of the Peeragogy Handbook
baseurl: "/peeragogy-ai-handbook"
url: "https://ftg-003.github.io"

# Multilingual settings
languages: ["en", "it"]
default_lang: "en"
exclude_from_localization: ["assets", "css", "js", "images"]
parallel_localization: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      ai_processable: true
      
  - scope:
      path: "_chapters/en"
    values:
      lang: "en"
      
  - scope:
      path: "_chapters/it"
    values:
      lang: "it"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
